---
- name: Example Playbook to apply cis_ubuntu_2004 role with all the default values.
  hosts: *  # or any grouping of hosts
  become: yes
  gather_facts: true
  roles:
    - cis_ubuntu_2004
  vars:
    ansible_python_interpreter: /usr/bin/python3

    # DISABLE 1.1.1.6 as it results with error | modprobe: FATAL: Module squashfs is builtin.
    ubuntu_2004_cis_section1_rule_1_1_1_6:  false
    ubuntu_2004_cis_section1_rule_1_3_1 :   false
    ubuntu_2004_cis_section1_rule_1_3_2 :   false
    ubuntu_2004_cis_section1_rule_1_4_1 :   false
    ubuntu_2004_cis_section1_rule_1_4_4 :   false
    ubuntu_2004_cis_section4_rule_4_2_1_6 : false
    ubuntu_2004_cis_section5_rule_5_3_4 :   false
